// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/** Migrate / db push / introspection için. Varsa DIRECT_URL (Neon direct) önceliklidir. */
function migrateDatasourceUrl(): string {
  const direct = process.env["DIRECT_URL"]?.trim();
  const database = process.env["DATABASE_URL"]?.trim();
  const url = direct || database || "";
  if (!url) {
    throw new Error(
      "DATABASE_URL tanımlı değil. CLI için web/.env veya ortam değişkenlerini kontrol et.",
    );
  }
  return url;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: migrateDatasourceUrl(),
  },
});
